events {}

http {

    upstream creation_service_cluster {
        server creation-a:8000;
        server creation-b:8000;
        server creation-c:8000;
    }

    upstream redirect_service_cluster {
        server redirect:8000;
    }

    server {

        listen 80;

        location = /create {
            proxy_pass http://creation_service_cluster;
        }

       

        location  / {
            proxy_pass http://redirect_service_cluster;
        }

    }
}